// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CanGauge250927

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_coolant;
extern lv_obj_t * ui_oiltemp;
extern lv_obj_t * ui_Boost;
extern lv_obj_t * ui_OilPressure;
extern lv_obj_t * ui_EGT;
extern lv_obj_t * ui_AFR;
extern lv_obj_t * ui_IAT;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_OiltempLogo;
extern lv_obj_t * ui_Turbo;
extern lv_obj_t * ui_AFRLogo;
extern lv_obj_t * ui_EGTLogo;
extern lv_obj_t * ui_CoolantLogo;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_GPS;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

