// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CanGauge250927

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_coolant = NULL;
lv_obj_t * ui_oiltemp = NULL;
lv_obj_t * ui_Boost = NULL;
lv_obj_t * ui_OilPressure = NULL;
lv_obj_t * ui_EGT = NULL;
lv_obj_t * ui_AFR = NULL;
lv_obj_t * ui_IAT = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_OiltempLogo = NULL;
lv_obj_t * ui_Turbo = NULL;
lv_obj_t * ui_AFRLogo = NULL;
lv_obj_t * ui_EGTLogo = NULL;
lv_obj_t * ui_CoolantLogo = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_GPS = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolant = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_coolant, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_coolant, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coolant, 0);
    lv_obj_set_y(ui_coolant, 27);
    lv_obj_set_align(ui_coolant, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_coolant, "50");
    lv_obj_set_style_text_font(ui_coolant, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oiltemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_oiltemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oiltemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oiltemp, -34);
    lv_obj_set_y(ui_oiltemp, 60);
    lv_obj_set_align(ui_oiltemp, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_oiltemp, "5.0");
    lv_obj_set_style_text_font(ui_oiltemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Boost = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Boost, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Boost, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Boost, 2);
    lv_obj_set_y(ui_Boost, -9);
    lv_obj_set_align(ui_Boost, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Boost, "0.00");
    lv_obj_clear_flag(ui_Boost, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Boost, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OilPressure = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_OilPressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OilPressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OilPressure, -34);
    lv_obj_set_y(ui_OilPressure, -60);
    lv_obj_set_align(ui_OilPressure, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_OilPressure, "4.2");
    lv_obj_set_style_text_align(ui_OilPressure, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OilPressure, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EGT = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_EGT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EGT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EGT, 0);
    lv_obj_set_y(ui_EGT, -15);
    lv_obj_set_align(ui_EGT, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_EGT, "720");
    lv_obj_set_style_text_font(ui_EGT, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AFR = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AFR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AFR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AFR, 30);
    lv_obj_set_y(ui_AFR, -60);
    lv_obj_set_align(ui_AFR, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_AFR, "1.00");
    lv_obj_set_style_text_font(ui_AFR, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IAT = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_IAT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IAT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IAT, 34);
    lv_obj_set_y(ui_IAT, 60);
    lv_label_set_text(ui_IAT, "24");
    lv_obj_set_style_text_font(ui_IAT, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 20);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "BOOST");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OiltempLogo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_OiltempLogo, &ui_img_3_png);
    lv_obj_set_width(ui_OiltempLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OiltempLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OiltempLogo, 72);
    lv_obj_set_y(ui_OiltempLogo, -69);
    lv_obj_set_align(ui_OiltempLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OiltempLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OiltempLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_OiltempLogo, 120);

    ui_Turbo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Turbo, &ui_img_4_png);
    lv_obj_set_width(ui_Turbo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Turbo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Turbo, 0);
    lv_obj_set_y(ui_Turbo, -38);
    lv_obj_set_align(ui_Turbo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Turbo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Turbo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Turbo, 150);

    ui_AFRLogo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_AFRLogo, &ui_img_5_png);
    lv_obj_set_width(ui_AFRLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AFRLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AFRLogo, -72);
    lv_obj_set_y(ui_AFRLogo, 25);
    lv_obj_set_align(ui_AFRLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AFRLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AFRLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_AFRLogo, 120);

    ui_EGTLogo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_EGTLogo, &ui_img_7_png);
    lv_obj_set_width(ui_EGTLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EGTLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EGTLogo, 0);
    lv_obj_set_y(ui_EGTLogo, 70);
    lv_obj_set_align(ui_EGTLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EGTLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_EGTLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_EGTLogo, 120);

    ui_CoolantLogo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_CoolantLogo, &ui_img_8_png);
    lv_obj_set_width(ui_CoolantLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoolantLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CoolantLogo, 0);
    lv_obj_set_y(ui_CoolantLogo, -104);
    lv_obj_set_align(ui_CoolantLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CoolantLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CoolantLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CoolantLogo, 120);

    ui_Image7 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image7, &ui_img_ansauglufttemperatur_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -74);
    lv_obj_set_y(ui_Image7, -72);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 120);

    ui_Image9 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image9, &ui_img_1614547736);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, 71);
    lv_obj_set_y(ui_Image9, 29);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 140);

    ui_GPS = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_GPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS, 91);
    lv_obj_set_y(ui_GPS, -7);
    lv_obj_set_align(ui_GPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPS, "GPS");
    lv_obj_set_style_text_color(ui_GPS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GPS, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_coolant = NULL;
    ui_oiltemp = NULL;
    ui_Boost = NULL;
    ui_OilPressure = NULL;
    ui_EGT = NULL;
    ui_AFR = NULL;
    ui_IAT = NULL;
    ui_Label7 = NULL;
    ui_OiltempLogo = NULL;
    ui_Turbo = NULL;
    ui_AFRLogo = NULL;
    ui_EGTLogo = NULL;
    ui_CoolantLogo = NULL;
    ui_Image7 = NULL;
    ui_Image9 = NULL;
    ui_GPS = NULL;

}
