// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CanGauge250927

#include "../ui.h"

void ui_comp_Bar1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Chart1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Slider1_create_hook(lv_obj_t * comp)
{
}
