// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CanGauge250927

#include "../ui.h"

// COMPONENT Bar1

lv_obj_t * ui_Bar1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Bar1;
    cui_Bar1 = lv_bar_create(comp_parent);
    lv_bar_set_value(cui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Bar1, 148);
    lv_obj_set_height(cui_Bar1, 22);
    lv_obj_set_x(cui_Bar1, 29);
    lv_obj_set_y(cui_Bar1, -13);
    lv_obj_set_align(cui_Bar1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(cui_Bar1, LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    lv_obj_set_flex_align(cui_Bar1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BAR1_NUM);
    children[UI_COMP_BAR1_BAR1] = cui_Bar1;
    lv_obj_add_event_cb(cui_Bar1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Bar1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Bar1_create_hook(cui_Bar1);
    return cui_Bar1;
}

