// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CanGauge250927

#ifndef _UI_COMP_CHART1_H
#define _UI_COMP_CHART1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Chart1
#define UI_COMP_CHART1_CHART1 0
#define _UI_COMP_CHART1_NUM 1
lv_obj_t * ui_Chart1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
