// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: CanGauge250927

#ifndef _CANGAUGE250927_UI_COMP_HOOK_H
#define _CANGAUGE250927_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Bar1_create_hook(lv_obj_t * comp);
void ui_comp_Chart1_create_hook(lv_obj_t * comp);
void ui_comp_Slider1_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
